"use client";

import React, { useState, useEffect, useMemo } from 'react';
import axios from 'axios';
import Cookies from 'js-cookie';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  History, Search, Download, Undo2, 
  ExternalLink, Printer, AlertCircle, Loader2 
} from 'lucide-react';
import { cn } from "@/lib/utils";
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// --- Types ---
interface PaymentHistory {
  id: string;
  customer: string;
  amount: number;
  method: 'Bank' | 'Cash' | 'Online';
  date: string;
  time: string;
  status: 'Completed' | 'Reversed';
  ledgerImpact: string;
}

export default function RecentPayments() {
  const [data, setData] = useState<PaymentHistory[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<'All' | 'Completed' | 'Reversed'>('All');

  const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL;

  // --- 1. Fetch Transaction History ---
  useEffect(() => {
    const fetchHistory = async () => {
      try {
        setLoading(true);
        const userId = Cookies.get('userId');
        const token = Cookies.get('auth_token');

        if (!userId) {
          setError("Session expired. Access Denied.");
          return;
        }

        const response = await axios.get(`${API_BASE_URL}/accounts/history`, {
          params: { userId },
          headers: { 'Authorization': `Bearer ${token}` }
        });

        setData(response.data);
      } catch (err: any) {
        console.error("History Sync Error:", err);
        setError(err.response?.data?.message || "Failed to fetch logs");
      } finally {
        setLoading(false);
      }
    };

    fetchHistory();
  }, [API_BASE_URL]);

  // --- 2. Search & Filter Logic ---
  const filteredHistory = useMemo(() => {
    return data.filter(item => {
      const matchesSearch = item.customer.toLowerCase().includes(search.toLowerCase()) || item.id.includes(search);
      const matchesFilter = filter === 'All' || item.status === filter;
      return matchesSearch && matchesFilter;
    });
  }, [search, filter, data]);

  // --- 3. Handle Reversal via API ---
  const handleReverse = async (id: string) => {
    if (confirm("System Protocol: Are you sure you want to reverse this ledger entry?")) {
      try {
        const token = Cookies.get('auth_token');
        const userId = Cookies.get('userId');

        await axios.post(`${API_BASE_URL}/accounts/reverse-transaction`, {
          transactionId: id,
          userId
        }, {
          headers: { 'Authorization': `Bearer ${token}` }
        });

        // Update local state for instant UI feedback
        setData(prev => prev.map(item => 
          item.id === id ? { ...item, status: 'Reversed' } : item
        ));
      } catch (err) {
        alert("System error during reversal. Transaction protected.");
      }
    }
  };

  // --- 4. PDF Generation ---
  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    doc.setFillColor(2, 6, 23);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.text("NEXUS FINANCE - TRANSACTION LOG", 14, 20);
    doc.setFontSize(8);
    doc.text(`CONFIDENTIAL REPORT • GENERATED BY: ${Cookies.get('userId')}`, 14, 30);

    const tableRows = filteredHistory.map(txn => [
      txn.id, txn.customer, txn.method, `PKR ${txn.amount.toLocaleString()}`, txn.date, txn.status
    ]);

    autoTable(doc, {
      startY: 45,
      head: [['TXN ID', 'Customer', 'Method', 'Amount', 'Date', 'Status']],
      body: tableRows,
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235] },
    });

    doc.save(`Nexus_Audit_Log_${new Date().getTime()}.pdf`);
  };

  if (loading) return (
    <div className="h-screen w-full flex flex-col items-center justify-center bg-[#020617]">
      <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: "linear" }} className="text-blue-500 mb-4">
        <Loader2 size={48} />
      </motion.div>
      <p className="text-[10px] font-black uppercase tracking-[0.4em] text-slate-500 italic">Reading Transaction Ledger...</p>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#020617] p-4 md:p-10 text-slate-300 font-sans print:bg-white">
      
      {/* HEADER */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-10 print:hidden">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-blue-500/10 rounded-lg"><History className="text-blue-500" size={20} /></div>
            <h1 className="text-3xl font-black text-white italic tracking-tighter uppercase">Transaction Log</h1>
          </div>
          <p className="text-[10px] font-bold text-slate-500 uppercase tracking-[0.3em] italic">Confirmed Financial Inflows • Real-time Sync</p>
        </motion.div>
        
        <div className="flex gap-3">
            <button onClick={() => window.print()} className="flex items-center gap-3 px-6 py-3 bg-white/5 border border-white/10 rounded-2xl text-[9px] font-black uppercase tracking-widest hover:bg-white/10 transition-all text-white">
                <Printer size={14} /> Print
            </button>
            <button onClick={handleDownloadPDF} className="flex items-center gap-3 px-6 py-3 bg-blue-600 rounded-2xl text-[9px] font-black uppercase tracking-widest hover:bg-blue-700 transition-all text-white shadow-lg shadow-blue-600/20">
                <Download size={14} /> Export PDF
            </button>
        </div>
      </div>

      {/* FILTERS */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-4 mb-8 print:hidden">
        <div className="lg:col-span-2 relative">
          <Search className="absolute left-6 top-1/2 -translate-y-1/2 text-slate-600" size={16} />
          <input 
            type="text" placeholder="SEARCH BY TRANSACTION ID OR CLIENT..." value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-[#050b1d] border border-white/5 rounded-2xl py-4 pl-14 pr-6 text-[10px] font-black uppercase tracking-widest outline-none focus:border-blue-500/50 text-white"
          />
        </div>
        <div className="flex gap-2 p-1 bg-[#050b1d] rounded-2xl border border-white/5">
          {(['All', 'Completed', 'Reversed'] as const).map((f) => (
            <button key={f} onClick={() => setFilter(f)} className={cn("flex-1 py-3 rounded-xl text-[8px] font-black uppercase tracking-widest transition-all", filter === f ? "bg-blue-600 text-white" : "text-slate-500 hover:text-white")}>
              {f}
            </button>
          ))}
        </div>
      </div>

      {/* TABLE */}
      <div className="bg-[#050b1d] border border-white/5 rounded-[2.5rem] overflow-hidden shadow-2xl print:border-none print:bg-white">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-white/5 bg-white/[0.01]">
                <th className="px-8 py-6 text-[9px] font-black text-slate-500 uppercase tracking-widest">Transaction / ID</th>
                <th className="px-8 py-6 text-[9px] font-black text-slate-500 uppercase tracking-widest">Client & Ledger</th>
                <th className="px-8 py-6 text-[9px] font-black text-slate-500 uppercase tracking-widest">Method</th>
                <th className="px-8 py-6 text-[9px] font-black text-slate-500 uppercase tracking-widest">Amount</th>
                <th className="px-8 py-6 text-[9px] font-black text-slate-500 uppercase tracking-widest text-right print:hidden">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              <AnimatePresence mode="popLayout">
                {filteredHistory.map((txn, idx) => (
                  <motion.tr key={txn.id} layout initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ delay: idx * 0.05 }} className="group hover:bg-white/[0.02] transition-colors">
                    <td className="px-8 py-6">
                      <div className="flex flex-col">
                        <span className="text-xs font-black text-white mb-1 uppercase print:text-black">{txn.id}</span>
                        <span className="text-[9px] font-bold text-slate-500 italic">{txn.date} • {txn.time}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6">
                      <div className="flex flex-col">
                        <span className="text-sm font-black text-slate-300 italic uppercase print:text-black">{txn.customer}</span>
                        <span className="text-[9px] font-bold text-slate-600 uppercase tracking-widest">{txn.ledgerImpact}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6">
                      <span className="text-[9px] font-black uppercase text-blue-400">{txn.method}</span>
                    </td>
                    <td className="px-8 py-6">
                      <div className="flex flex-col">
                        <span className={cn("text-sm font-black italic", txn.status === 'Reversed' ? "text-rose-500 line-through" : "text-emerald-500 print:text-black")}>
                          PKR {txn.amount.toLocaleString()}
                        </span>
                        <span className="text-[8px] font-bold uppercase text-slate-500">{txn.status}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6 text-right print:hidden">
                      <div className="flex items-center justify-end gap-2">
                        {txn.status === 'Completed' && (
                          <button onClick={() => handleReverse(txn.id)} className="p-3 bg-white/5 rounded-xl hover:bg-rose-600 hover:text-white transition-all text-rose-500 shadow-sm"><Undo2 size={14} /></button>
                        )}
                        <button className="p-3 bg-white/5 rounded-xl hover:bg-blue-600 hover:text-white transition-all text-slate-500"><ExternalLink size={14} /></button>
                      </div>
                    </td>
                  </motion.tr>
                ))}
              </AnimatePresence>
            </tbody>
          </table>
        </div>
      </div>
      
      {!loading && filteredHistory.length === 0 && (
        <div className="py-20 text-center border border-dashed border-white/10 rounded-[2.5rem] mt-4">
            <AlertCircle className="mx-auto text-slate-700 mb-4" size={40} />
            <p className="text-[10px] font-black text-slate-600 uppercase tracking-[0.5em]">{error ? error : "No synchronization found"}</p>
        </div>
      )}
    </div>
  );
}